

all:	example_one example_two example_three example_four example_five example_six example_seven example_eight example_nine example_ten example_eleven

example_one:	example_one.c Makefile
	gcc example_one.c -o example_one $(INC) $(LIB)

example_two:	example_two.c Makefile
	gcc example_two.c -o example_two $(INC) $(LIB)

example_three:	example_three.c Makefile
	gcc example_three.c -o example_three $(INC) $(LIB)

example_four:	example_four.c Makefile
	gcc example_four.c -o example_four $(INC) $(LIB)

example_five:	example_five.c Makefile
	gcc example_five.c -o example_five $(INC) $(LIB)

example_six:	example_six.c Makefile
	gcc example_six.c -o example_six $(INC) $(LIB)

example_seven:	example_seven.c Makefile
	gcc example_seven.c -o example_seven $(INC) $(LIB)

example_eight:	example_eight.c Makefile
	gcc example_eight.c -o example_eight $(INC) $(LIB)

example_nine:	example_nine.c Makefile
	gcc example_nine.c -o example_nine $(INC) $(LIB)

example_ten:	example_ten.c Makefile
	gcc example_ten.c -o example_ten $(INC) $(LIB)

example_eleven:	example_eleven.c Makefile
	gcc example_eleven.c -o example_eleven $(INC) $(LIB)

clean:
	rm -f example_one example_two example_three example_four example_five example_six example_seven example_eight example_nine example_ten example_eleven

